import mongoose, { Schema, type InferSchemaType, type HydratedDocument } from 'mongoose';
import { LIMITS } from './constants.js';

const shoppingItemSchema = new Schema(
  {
    /**
     * Generated by whichever client created the item, and stable across
     * devices. It is what makes merging possible: the same ingredient added
     * from two devices is one item, not two.
     */
    id: { type: String, required: true },
    amount: { type: String, default: '', maxlength: LIMITS.ingredientAmount },
    name: { type: String, required: true, maxlength: LIMITS.ingredientName },
    recipeId: { type: String, default: '' },
    recipeTitle: { type: String, default: '', maxlength: LIMITS.title },
    checked: { type: Boolean, default: false },
    addedAt: { type: Number, default: () => Date.now() },
  },
  { _id: false },
);

/**
 * A shopping list that follows the user between devices.
 *
 * The local list stays as the offline cache — a shopping list that only works
 * with a signal is not much use in a supermarket — and this is the copy that
 * survives switching phones. See `mergeItems` in routes/shopping-list.ts for
 * the reconciliation rule.
 */
const shoppingListSchema = new Schema(
  {
    user: { type: String, required: true, unique: true, index: true },
    items: { type: [shoppingItemSchema], default: [] },
  },
  { timestamps: true },
);

export type ShoppingListDoc = HydratedDocument<InferSchemaType<typeof shoppingListSchema>>;
export type ShoppingItem = InferSchemaType<typeof shoppingItemSchema>;

export const ShoppingList = mongoose.model('ShoppingList', shoppingListSchema);
